remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Nova Coimbra Liberal
description: Projeto para o GCL de Coimbra - Novas Caras,Novos Caminhos
base: / 
logo: /assets/logo.jpg
people: /people.html
join: /join.html
ideas: /ideas.html
layout: default
background-image: /assets/logo.jpg
background-size: 100% auto;
github_pages:
  jekyll-mentions: false
