remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Nova Coimbra Liberal
description: Projeto para o GCL de Coimbra
logo: /logo.png
layout: default
github_pages:
  jekyll-mentions: false
